eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8686/eureka/
server:
    port: 8787
spring:
  cloud:
    bus:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
        name: shiping-service
  config:
    import: "optional:configserver:http://localhost:8888"

test:
  username: minhtxhcdsyucvysdvcysd
